# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap



class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(576, 375)
        image_path = "resource/PersonPicture.png"
        pixmap = QPixmap(image_path)
        self.AvatarWidget = AvatarWidget(LoginWindow)
        self.AvatarWidget.setPixmap(pixmap)
        self.AvatarWidget.setGeometry(QtCore.QRect(240, 40, 200, 200))
        self.AvatarWidget.setRadius(50)
        self.AvatarWidget.setObjectName("AvatarWidget")
        self.BodyLabel = BodyLabel(LoginWindow)
        self.BodyLabel.setGeometry(QtCore.QRect(100, 180, 63, 19))
        self.BodyLabel.setObjectName("BodyLabel")
        self.BodyLabel_2 = BodyLabel(LoginWindow)
        self.BodyLabel_2.setGeometry(QtCore.QRect(100, 230, 51, 21))
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.PrimaryPushButton = PrimaryPushButton(LoginWindow)
        self.PrimaryPushButton.setGeometry(QtCore.QRect(220, 290, 153, 32))
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.LineEdit = LineEdit(LoginWindow)
        self.LineEdit.setGeometry(QtCore.QRect(170, 170, 271, 33))
        self.LineEdit.setObjectName("LineEdit")
        self.PasswordLineEdit = PasswordLineEdit(LoginWindow)
        self.PasswordLineEdit.setGeometry(QtCore.QRect(170, 220, 271, 33))
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "HR-Manager Login"))
        self.BodyLabel.setText(_translate("LoginWindow", "用户名："))
        self.BodyLabel_2.setText(_translate("LoginWindow", "密码："))
        self.PrimaryPushButton.setText(_translate("LoginWindow", "登录"))
from qfluentwidgets import AvatarWidget, BodyLabel, LineEdit, PasswordLineEdit, PrimaryPushButton


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QWidget()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
