# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\EmployeesManage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DepartmentManage(object):
    def setupUi(self, DepartmentManage):
        DepartmentManage.setObjectName("DepartmentManage")
        DepartmentManage.resize(966, 668)
        self.layoutWidget = QtWidgets.QWidget(DepartmentManage)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 931, 651))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TableView = TableView(self.layoutWidget)
        self.TableView.setObjectName("TableView")
        self.horizontalLayout.addWidget(self.TableView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.PushButton = PushButton(self.layoutWidget)
        self.PushButton.setObjectName("PushButton")
        self.verticalLayout.addWidget(self.PushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.PushButton_2 = PushButton(self.layoutWidget)
        self.PushButton_2.setObjectName("PushButton_2")
        self.verticalLayout.addWidget(self.PushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.PushButton_3 = PushButton(self.layoutWidget)
        self.PushButton_3.setObjectName("PushButton_3")
        self.verticalLayout.addWidget(self.PushButton_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.PushButton_4 = PushButton(self.layoutWidget)
        self.PushButton_4.setObjectName("PushButton_4")
        self.verticalLayout.addWidget(self.PushButton_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.PushButton_5 = PushButton(self.layoutWidget)
        self.PushButton_5.setObjectName("PushButton_5")
        self.verticalLayout.addWidget(self.PushButton_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(DepartmentManage)
        QtCore.QMetaObject.connectSlotsByName(DepartmentManage)

    def retranslateUi(self, DepartmentManage):
        _translate = QtCore.QCoreApplication.translate
        DepartmentManage.setWindowTitle(_translate("DepartmentManage", "DepartmentManage"))
        self.PushButton.setText(_translate("DepartmentManage", "Quit"))
        self.PushButton_2.setText(_translate("DepartmentManage", "Submit"))
        self.PushButton_3.setText(_translate("DepartmentManage", "Revert"))
        self.PushButton_4.setText(_translate("DepartmentManage", "Add"))
        self.PushButton_5.setText(_translate("DepartmentManage", "Delete"))


from qfluentwidgets import PushButton, TableView

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    DepartmentManage = QtWidgets.QWidget()
    ui = Ui_DepartmentManage()
    ui.setupUi(DepartmentManage)
    DepartmentManage.show()
    sys.exit(app.exec_())
